/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SampleModule"
 * 	found in "msg.asn"
 * 	`asn1c -no-gen-example`
 */

#include "MessageAB.h"

static asn_TYPE_member_t asn_MBR_MessageAB_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MessageAB, msgType),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"msgType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MessageAB, unqID),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"unqID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MessageAB, msg),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"msg"
		},
};
static const ber_tlv_tag_t asn_DEF_MessageAB_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MessageAB_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* unqID */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 0, 0, 1 }, /* msgType */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 2, -1, 0 } /* msg */
};
static asn_SEQUENCE_specifics_t asn_SPC_MessageAB_specs_1 = {
	sizeof(struct MessageAB),
	offsetof(struct MessageAB, _asn_ctx),
	asn_MAP_MessageAB_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MessageAB = {
	"MessageAB",
	"MessageAB",
	&asn_OP_SEQUENCE,
	asn_DEF_MessageAB_tags_1,
	sizeof(asn_DEF_MessageAB_tags_1)
		/sizeof(asn_DEF_MessageAB_tags_1[0]), /* 1 */
	asn_DEF_MessageAB_tags_1,	/* Same as above */
	sizeof(asn_DEF_MessageAB_tags_1)
		/sizeof(asn_DEF_MessageAB_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MessageAB_1,
	3,	/* Elements count */
	&asn_SPC_MessageAB_specs_1	/* Additional specs */
};

