/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SampleModule"
 * 	found in "msg.asn"
 * 	`asn1c -no-gen-example`
 */

#ifndef	_MessageBA_H_
#define	_MessageBA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MessageBA */
typedef struct MessageBA {
	UTF8String_t	 msgType;
	long	 unqID;
	UTF8String_t	 msg;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageBA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageBA;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageBA_H_ */
#include <asn_internal.h>
